version: '3.8'
services:
    php-apache-environment:
        container_name: php
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html/
        ports:
            - 8000:80
    mysql:
        container_name: kanban_db
        image: mysql
        platform: linux/amd64
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: db
            MYSQL_USER: kanban_user
            MYSQL_PASSWORD: 123
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql